implement disableHighlight; pass inputValue to formatter
mskocik/svelecte pull request #20
Opened 2021-05-03 19:59 UTC by kamholz

Let me know if you think this is a reasonable change. I put the two changes together because the main reason I can think of to pass inputValue to the formatter is so it can handle the highlighting.

2021-05-04 08:05 UTC, mskocik requested changes
Initially I was thinking about way to provide custom highlight function, but it's too complicated, This is much simpler solution and custom highlighting can be handled in formatter as you said.

So please update given code and also update the docs. I will be happy to merge it afterwards.

2021-05-04 08:05 UTC, mskocik commented on src/lib/utils.js
> +  if (!disableHighlight) {
This `if` is unnecessary, because you could extend condition on line 59 for this.

2021-05-04 21:11 UTC, kamholz commented
Sorry for the forced pushes (git is not my forte). I think this is good now. Let me know!

2021-05-05 06:23 UTC, mskocik approved these changes

2021-05-05 06:24 UTC, merged